# Generated by Django 3.0.4 on 2020-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFakenews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titular',
            field=models.CharField(max_length=100),
        ),
    ]
